strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'VS2017-Win2016'

trigger:
- zezo

pool:
  vmImage: $(imageName)

variables:
  solution: 'Zezo.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: Install .NET Core
  inputs:
    version: '2.1.401' 

- script: dotnet restore Zezo.sln
  displayName: Restore Solution

- script: dotnet build Zezo.sln
  displayName: Build Solution

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: 'test/Zezo**Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
