# Reference: https://aka.ms/yaml
# Things to note:
# - Powershell session profiles do not work because the scripts are run with -NoProfile

trigger:
- master

pool:
vmImage: 'ubuntu-16.04'

steps:
- script: git submodule update --init
  displayName: 'git submodule'
- script: |
    echo '$(dockerPassword)' | docker login -u ztl8702 --password-stdin
  displayName: Log in to DockerHub
- script: |
    ./build.sh
  displayName: Build and push
