version: '2'
services:
  postgres:
    image: postgres:9.6
    environment: 
      POSTGRES_DB: crowdsource
    volumes:
      - /var/lib/postgresql/data
      - /root/backups
  web:
    image: crowdsource_web
#    build:
#      dockerfile: Dockerfile
#      context: ./src/CrowdSource
    depends_on:
      - postgres
    links:
      - postgres:pg