# Dockerfile for publishing code for production

FROM microsoft/aspnetcore-build:1.1-msbuild
WORKDIR /app

COPY CrowdSource.csproj .
RUN dotnet restore

COPY . . 
RUN dotnet restore && dotnet bundle && dotnet publish --output /out/ --configuration Release
